### ISSUE TITLE
Quantity box-shadow

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/boutique#18]
![](http://cld.wthms.co/18ZKJ+)

It does not look good to me, is it wanted like that?

**Comment by jameskoster** [comment]
Y U still running 2.2.*? :p

**Comment by SiR-DanieL** [comment]
That's the demo xD

**Comment by jameskoster** [comment]
@kloon would you mind updating WooCommerce to 2.3 on the demo servers?
