### ISSUE TITLE
Storefront Designer Integration

### ISSUE THREAD

**Issue by RiaanKnoetze** [woothemes/boutique#26]
Link to ticket: https://woothemes.zendesk.com/agent/tickets/355389

With both Boutique and Storefront Designer activated, none of the items you would expect from Storefront Designer is showing in the Customizer panels.

Header: http://cld.wthms.co/1417b/24qMuOei
Footer: http://cld.wthms.co/7sGp/2pWcmhiL
Layout: http://cld.wthms.co/1g0hm/DnklqYBA
Buttons: http://cld.wthms.co/1baEw/1f0qAaVd
Typography: http://cld.wthms.co/1aCgk/4RPinUpL

**Comment by jameskoster** [comment]
Not really a bug. But we should look to add integration for the next release.
