### ISSUE TITLE
Unable to process this payment, please try again or use alternative method. Stripe

### ISSUE THREAD

**Issue by Ruben2600** [woothemes/boutique#80]
Hello,

On my Woocommerce checkout page, I get this message when I pay with a (correct) visa / mastercard card with connecting Stripe: 
**Unable to process this payment, please try again or use alternative method.**

Can anyone help me fix this / or how to see this in the logs and where?
Answers are appreciated.

Thanks!

**Comment by nielslange** [comment]
Hello @Ruben2600 👋

This problem sounds directly related to the Stripe plugin and not related to the Boutique theme. The error message that you mentioned had been reported a few times before and on https://wordpress.org/search/Unable+to+process+this+payment%2C+please+try+again+or+use+alternative+method you can find the corresponding reports.

As this report is unrelated to this theme, I'm going to close this ticket now and hope that you're able to solve the problem, that you're currently facing, with the link that I shared before.
