### ISSUE TITLE
Lighten background color for payment method icons in the Cart block

### ISSUE THREAD

**Issue by nerrad** [woothemes/boutique#81]
## Describe the bug

The cart block has a background where the payment method icons appear that could create legibility issues with different card colors. Screenshot:

![screenshot](https://user-images.githubusercontent.com/69914963/107653319-40843b00-6c60-11eb-9850-fc7d1d5248be.png)

## To Reproduce
1. Install and activate [WooCommerce Blocks feature plugin](https://wordpress.org/plugins/woo-gutenberg-products-block/).
2. You will need to install and configure Stripe Payment Extension (or WooCommerce Payments) to be able to see credit card icons.
2. Insert the Cart block on a page.
3. Add some items to the cart then view the page you added the Cart block to.
4. See the Credit Card icons and the background color as in the screenshot.

## Expected behavior

A lighter background for the credit card icons visible in the cart page. Suggested color `#EAEAEA`

**Comment by luislard** [comment]
@nerrad @jconroy 
Same issue reported in https://github.com/woocommerce/deli/issues/57 
See my comment in: https://github.com/woocommerce/deli/pull/60#issue-625214195

Best,
Luis

**Comment by nerrad** [comment]
See my comment [here](https://github.com/woocommerce/deli/pull/60#issuecomment-831355426)

**Comment by luislard** [comment]
@nerrad Please confirm the solution in https://github.com/woocommerce/deli/pull/67 is what is need to be done, if yes please reassign the ticket to me.

**Comment by nerrad** [comment]
Yup the approach in https://github.com/woocommerce/deli/pull/67 is great! Thanks.

**Comment by luislard** [comment]
Hello @nerrad ,
The default color for the button text is very dark #2b2b2b,

![image](https://user-images.githubusercontent.com/17932063/122379505-37d1a780-cf67-11eb-9738-abc361d55857.png)

Lets use the alternate button text color:
![image](https://user-images.githubusercontent.com/17932063/122379997-b3cbef80-cf67-11eb-9a61-fce9bdcaaa3a.png)
